inventory:
  - product_id: TECH007
    name: Smartphone
    category: Electronics
    price: 799.99
    in_stock: 100
  - product_id: HOME101
    name: Coffee Maker
    category: Appliances
    price: 49.99
    in_stock: 75
